GET http://localhost:8080/user
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJfZWRpdG9yIiwicGFzc3dvcmQiOiIxMjM0NTYiLCJpYXQiOjE2Mjg3NTc0NTYsImV4cCI6MTYyODc1NzQ3MX0.wyGWUmgbsECz7gNEav7oYR9y0YN-diK4xGn7ANdvk8U

###

POST http://localhost:8080/users/login
Content-Type: application/json

{
  "username": "user_editor",
  "password": "123456"
}

###
POST http://localhost:8080/refreshToken
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhvbGV0ZXgiLCJpYXQiOjE2MjA0NzQxODV9.I8lKqN5PLE3Vz103O5Ml7ePJWsUksJoeA81uYFeCc6o"
}

###
POST http://localhost:8080/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhvbGV0ZXgiLCJpYXQiOjE2MjA0NzQxODV9.I8lKqN5PLE3Vz103O5Ml7ePJWsUksJoeA81uYFeCc6o"
}